# Generated by Django 4.1.6 on 2023-04-10 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bell_Timing',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('c_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time', 'end_time'],
                'unique_together': {('owner', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('c_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('c_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-code'],
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_per_week', models.IntegerField(default=1)),
                ('lesson_length', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('c_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom')),
                ('groups', models.ManyToManyField(to='timetable.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Working_Day',
            fields=[
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('c_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Time_Off',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('c_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('bell_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.bell_timing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.working_day')),
            ],
            options={
                'ordering': ['working_day', 'bell_timing'],
                'unique_together': {('owner', 'bell_timing', 'working_day')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('c_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time_off', models.ManyToManyField(to='timetable.time_off')),
            ],
            options={
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('c_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time_off', models.ManyToManyField(to='timetable.time_off')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SemGrpCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lesson')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='time_off',
            field=models.ManyToManyField(to='timetable.time_off'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(to='timetable.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='time_off',
            field=models.ManyToManyField(to='timetable.time_off'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('owner', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('owner', 'code')},
        ),
    ]
