# Generated by Django 4.1.5 on 2023-01-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bell_Timing',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Working_Day',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Semester_Group',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester')),
            ],
            options={
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Teacher_Time_Off',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bell_timing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.bell_timing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher')),
                ('working_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.working_day')),
            ],
            options={
                'unique_together': {('owner', 'teacher_id', 'bell_timing_id', 'working_day_id')},
            },
        ),
        migrations.CreateModel(
            name='Subject_Time_Off',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bell_timing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.bell_timing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('working_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.working_day')),
            ],
            options={
                'unique_together': {('owner', 'subject_id', 'bell_timing_id', 'working_day_id')},
            },
        ),
        migrations.CreateModel(
            name='Semester_Time_Off',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bell_timing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.bell_timing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester')),
                ('working_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.working_day')),
            ],
            options={
                'unique_together': {('owner', 'semester_id', 'bell_timing_id', 'working_day_id')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_per_week', models.IntegerField(default=1)),
                ('is_lab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester_group')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher')),
            ],
            options={
                'unique_together': {('owner', 'lesson_per_week', 'classroom_id', 'subject_id', 'semester_id', 'semester_group_id')},
            },
        ),
        migrations.CreateModel(
            name='Classroom_Time_Off',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bell_timing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.bell_timing')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('working_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.working_day')),
            ],
            options={
                'unique_together': {('owner', 'classroom_id', 'bell_timing_id', 'working_day_id')},
            },
        ),
    ]
