# Generated by Django 4.1.5 on 2023-01-25 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester_group',
            unique_together={('owner', 'code', 'semester_id')},
        ),
    ]
