# Generated by Django 4.1.6 on 2023-04-10 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bell_timing',
            name='c_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='c_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='group',
            name='c_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='subject',
            name='c_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='c_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='time_off',
            name='c_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='working_day',
            name='c_id',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
    ]
