# Generated by Django 4.1.6 on 2023-03-18 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('owner', 'teacher', 'lesson_per_week', 'classroom', 'subject', 'semester', 'semester_group')},
        ),
    ]
