# Generated by Django 4.1.6 on 2023-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_lab',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='semester_group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='semester',
            field=models.ManyToManyField(to='timetable.semester'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='semester_group',
            field=models.ManyToManyField(to='timetable.semester_group'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(to='timetable.teacher'),
        ),
    ]
