# Generated by Django 4.1.5 on 2023-01-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_semester_group_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom_time_off',
            old_name='bell_timing_id',
            new_name='bell_timing',
        ),
        migrations.RenameField(
            model_name='classroom_time_off',
            old_name='working_day_id',
            new_name='working_day',
        ),
        migrations.RenameField(
            model_name='semester_time_off',
            old_name='bell_timing_id',
            new_name='bell_timing',
        ),
        migrations.RenameField(
            model_name='semester_time_off',
            old_name='working_day_id',
            new_name='working_day',
        ),
        migrations.RenameField(
            model_name='subject_time_off',
            old_name='bell_timing_id',
            new_name='bell_timing',
        ),
        migrations.RenameField(
            model_name='subject_time_off',
            old_name='working_day_id',
            new_name='working_day',
        ),
        migrations.RenameField(
            model_name='teacher_time_off',
            old_name='bell_timing_id',
            new_name='bell_timing',
        ),
        migrations.RenameField(
            model_name='teacher_time_off',
            old_name='working_day_id',
            new_name='working_day',
        ),
    ]
