# Generated by Django 4.1.2 on 2022-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_professor_owner_subject_owner_timing_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='semseter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
