# Generated by Django 4.1.6 on 2023-04-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_working_day_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time_off',
            options={'ordering': ['working_day', 'bell_timing']},
        ),
    ]
