# Generated by Django 4.1.6 on 2023-03-20 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0003_alter_lesson_unique_together_alter_lesson_is_lab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester_group',
            old_name='semester_id',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='semester_time_off',
            old_name='semester_id',
            new_name='semester',
        ),
        migrations.AlterUniqueTogether(
            name='semester_group',
            unique_together={('owner', 'code', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='semester_time_off',
            unique_together={('owner', 'semester', 'bell_timing', 'working_day')},
        ),
    ]
