# Generated by Django 4.1.5 on 2023-02-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_rename_classroom_id_lesson_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='semesters',
            field=models.ManyToManyField(to='timetable.semester'),
        ),
    ]
