# Generated by Django 4.1.2 on 2022-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_year_semseter_alter_timing_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='semseter',
            field=models.IntegerField(),
        ),
    ]
