# Generated by Django 4.1.6 on 2023-04-04 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0004_alter_time_off_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester_group',
            unique_together={('owner', 'code')},
        ),
        migrations.AddField(
            model_name='semester',
            name='groups',
            field=models.ManyToManyField(to='timetable.semester_group'),
        ),
        migrations.RemoveField(
            model_name='semester_group',
            name='semester',
        ),
    ]
