# Generated by Django 4.1.6 on 2023-03-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_rename_semester_id_semester_group_semester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='is_lab',
            new_name='lesson_length',
        ),
    ]
