# Generated by Django 4.1.6 on 2023-04-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_semester_group_unique_together_semester_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='semester_group',
        ),
        migrations.CreateModel(
            name='SemGrpCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester_group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lesson')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='semgrp',
            field=models.ManyToManyField(through='timetable.SemGrpCombo', to='timetable.semester'),
        ),
    ]
