# Generated by Django 4.1.2 on 2022-10-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_year_semseter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='semseter',
            new_name='semester',
        ),
    ]
