# Generated by Django 4.1.6 on 2023-04-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_lesson_semester_group_semgrpcombo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='semgrp',
            new_name='semesters',
        ),
    ]
