# Generated by Django 4.1.6 on 2023-04-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_rename_semgrp_lesson_semesters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
