# Generated by Django 4.1.2 on 2022-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_rename_semseter_year_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='time_to',
        ),
        migrations.AddField(
            model_name='timing',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='one_slot_interval',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='skip_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='skip_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
