# Generated by Django 4.1.6 on 2023-04-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_rename_teacher_lesson_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='semesters',
        ),
    ]
