# Generated by Django 4.1.2 on 2022-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_timing_time_from_remove_timing_time_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slot_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecture_in_a_week',
            field=models.IntegerField(default=1),
        ),
    ]
