# Generated by Django 4.1.6 on 2023-04-06 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0009_remove_lesson_semesters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Semester_Group',
            new_name='Group',
        ),
    ]
