# Generated by Django 4.1.2 on 2022-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_subject_slot_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='year',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='professor',
            name='nick_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='day',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='semester',
            field=models.IntegerField(unique=True),
        ),
    ]
