# Generated by Django 4.1.6 on 2023-04-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_rename_semester_group_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-code']},
        ),
    ]
