# Generated by Django 4.1.2 on 2022-11-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_remove_subject_lecture_in_a_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subject'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.IntegerField(default=1),
        ),
    ]
