# Generated by Django 4.1.2 on 2022-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_group_subject_alter_group_group_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group_lecture_in_a_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='slot_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='whole_lecture_in_a_week',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
