# Generated by Django 4.1.2 on 2022-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_alter_professor_nick_name_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='room',
        ),
        migrations.AddField(
            model_name='subject',
            name='room',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
